apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: ratings-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings-app-deployment
    spec:
      containers:
        - name: ratings-app-container
          image: rso6315/ratings-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_SERVER_BASE-URL
              value: http://35.246.208.18/ratings-service
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: third-cluster
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: MONGO_USERNAME
              value: mongo
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ratings-mongo-pass
                  key: MONGO_PASSWORD
            - name: MONGO_HOST
              value: ratings-db.e-store
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: db
            - name: MONGO_DEFAULT-COLLECTION
              value: ratings-service
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings-service
  name: ratings-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31015
      targetPort: 8080
      protocol: TCP
  selector:
    app: ratings-app-deployment
