apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: ratings-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings-app-deployment
    spec:
      containers:
        - name: ratings-app-container
          image: rso6315/ratings-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:mongo://ratings-db.e-store:27017/ratings-service
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ratings-mongo-pass
                  key: MONGO_PASSWORD
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings-service
  name: ratings-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31015
      targetPort: 8080
      protocol: TCP
  selector:
    app: ratings-app-deployment