apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-db-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: ratings-db-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ratings-db-deployment
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongo
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongo
            - name: MONGO_INITDB_DATABASE
              value: db

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ratings-db
  name: ratings-db
  namespace: e-store
spec:
  type: ClusterIP
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: ratings-db-deployment1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ratings-db-volume
  labels:
    type: local
  namespace: e-store
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data